// ===================================================
//  MealMutt — Recipe & Safety Data
// ===================================================

const RECIPES = [
  // ——— CHICKEN ———
  {
    id: "chicken-rice-veggie",
    name: "Classic Chicken & Rice",
    emoji: "🍚",
    protein: "chicken",
    desc: "A vet-approved staple: lean chicken, brown rice, and mixed veggies.",
    tags: ["Easy", "Vet Fave", "🍗 Chicken", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 420,   // per 8 oz batch serving
    macros: { protein: 50, fat: 20, carbs: 30 },
    // Ingredients given per 1 lb body weight per day → scaled in app
    // Base batch = ~8 oz cooked (serves 1 day for a 25-lb dog)
    ingredients: [
      { qty: 6,  unit: "oz", item: "boneless skinless chicken breast, diced" },
      { qty: 2,  unit: "oz", item: "brown rice (dry measure)" },
      { qty: 1,  unit: "oz", item: "carrots, finely chopped" },
      { qty: 0.5,unit: "oz", item: "frozen peas" },
      { qty: 0.5,unit: "oz", item: "spinach, finely chopped" },
      { qty: 1,  unit: "tsp", item: "fish oil (omega-3 supplement)" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Rinse brown rice and cook according to package — use plain water, no salt.",
      "While rice cooks, dice chicken breast into small, bite-sized pieces.",
      "Boil or steam chicken pieces for 12–15 minutes until fully cooked through (no pink).",
      "Steam or microwave carrots for 3–4 minutes until soft and mashable.",
      "Combine cooked rice, chicken, carrots, peas, and spinach in a large bowl.",
      "Let the mixture cool completely to room temperature before serving or storing.",
      "Drizzle fish oil over the portion before serving for omega-3 boost.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Dice everything small — dogs don't chew much! Pea size or smaller for toy breeds. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Store in airtight container for up to 4 days" },
      { label: "Freezer", value: "Freeze in daily portions for up to 3 months" },
      { label: "Serving Temp", value: "Room temperature or slightly warm — never hot" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight (see calculator)" },
    ],
    safeIngredients: ["Cooked chicken (boneless)", "Brown rice", "Carrots", "Peas", "Spinach", "Fish oil", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No cooked bones", "No grapes or raisins"],
    nutritionPerServing: { calories: 420, protein: "52g", fat: "9g", carbs: "28g", fiber: "3g" },
    allergens: ["chicken", "fish", "pea"],
  },

  {
    id: "chicken-sweet-potato",
    name: "Chicken & Sweet Potato",
    emoji: "🍠",
    protein: "chicken",
    desc: "Sweet potato provides fiber and beta-carotene — great for digestion and coat.",
    tags: ["Easy", "Digestion", "🍗 Chicken", "~25 min"],
    cookTime: 25,
    difficulty: "Easy",
    servingCalories: 390,
    macros: { protein: 45, fat: 18, carbs: 37 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "boneless chicken thigh, diced" },
      { qty: 3,  unit: "oz", item: "sweet potato, cubed" },
      { qty: 1,  unit: "oz", item: "green beans, chopped" },
      { qty: 0.5,unit: "oz", item: "blueberries (antioxidants)" },
      { qty: 1,  unit: "tsp", item: "coconut oil" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Peel and cube sweet potato into ½-inch pieces.",
      "Boil sweet potato for 10–12 minutes until fork-tender, then drain.",
      "While sweet potato cooks, dice chicken thigh into small pieces.",
      "Cook chicken in a dry pan over medium heat for 8–10 minutes until no pink remains.",
      "Steam green beans for 4–5 minutes until soft.",
      "Mash the sweet potato lightly — this helps smaller dogs eat it easier.",
      "Mix everything together with coconut oil and let cool fully before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Leave the sweet potato slightly chunky for larger dogs, fully mashed for puppies and small breeds. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 3–4 days in airtight container" },
      { label: "Freezer", value: "Freeze flat in zip-lock bags up to 2 months" },
      { label: "Serving Temp", value: "Room temp — microwave 10–15 sec if from fridge" },
      { label: "Daily Portion", value: "See calculator above for your dog's portion" },
    ],
    safeIngredients: ["Chicken thigh", "Sweet potato", "Green beans", "Blueberries", "Coconut oil", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No butter or salt", "No onion powder", "No macadamia nuts", "No xylitol"],
    nutritionPerServing: { calories: 390, protein: "44g", fat: "11g", carbs: "32g", fiber: "4g" },
    allergens: ["chicken"],
  },

  // ——— BEEF ———
  {
    id: "beef-veggie-bowl",
    name: "Beef & Veggie Bowl",
    emoji: "🥩",
    protein: "beef",
    desc: "Lean ground beef with mixed vegetables — iron-rich and protein-packed.",
    tags: ["Iron-Rich", "High Protein", "🥩 Beef", "~20 min"],
    cookTime: 20,
    difficulty: "Easy",
    servingCalories: 480,
    macros: { protein: 55, fat: 28, carbs: 17 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "lean ground beef (90/10 or leaner)" },
      { qty: 2,  unit: "oz", item: "zucchini, diced small" },
      { qty: 1.5,unit: "oz", item: "broccoli florets, finely chopped" },
      { qty: 1,  unit: "oz", item: "brown rice, cooked" },
      { qty: 0.5,unit: "oz", item: "carrots, shredded" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook lean ground beef in a pan over medium heat, breaking it apart as it cooks.",
      "Drain excess fat — too much fat can upset your dog's stomach.",
      "Steam broccoli and zucchini for 4–5 minutes until tender.",
      "Cook brown rice separately in plain water until done.",
      "Mix beef, vegetables, and rice together in a bowl.",
      "Let mixture cool to room temperature — feel the bottom of the bowl with your palm.",
      "Serve appropriate portion based on your dog's weight.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Use 90% lean ground beef or leaner to keep fat content low. High fat can cause pancreatitis. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "3–4 days in a sealed container" },
      { label: "Freezer", value: "Up to 3 months in portioned bags" },
      { label: "Serving Temp", value: "Cool to room temp before serving" },
      { label: "Daily Portion", value: "Calculated above based on body weight" },
    ],
    safeIngredients: ["Lean ground beef", "Zucchini", "Broccoli (small amounts)", "Brown rice", "Carrots", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No seasoning or spices", "No onions or garlic", "No soy sauce", "No fatty beef cuts"],
    nutritionPerServing: { calories: 480, protein: "58g", fat: "14g", carbs: "18g", fiber: "3g" },
    allergens: ["beef"],
  },

  {
    id: "beef-liver-oats",
    name: "Beef Liver & Oats",
    emoji: "🫀",
    protein: "beef",
    desc: "Liver is a nutrient powerhouse — vitamins A, B12, and iron. Use in moderation.",
    tags: ["Nutrient Dense", "Senior Fave", "🥩 Beef", "~25 min"],
    cookTime: 25,
    difficulty: "Medium",
    servingCalories: 360,
    macros: { protein: 52, fat: 22, carbs: 26 },
    ingredients: [
      { qty: 3,  unit: "oz", item: "beef liver, sliced" },
      { qty: 3,  unit: "oz", item: "lean ground beef" },
      { qty: 2,  unit: "oz", item: "rolled oats (plain, not instant)" },
      { qty: 1,  unit: "oz", item: "pumpkin puree (canned, plain)" },
      { qty: 0.5,unit: "oz", item: "egg (about ½ large egg)" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Bring a small pot of water to a boil, then cook beef liver for 8–10 minutes.",
      "Let liver cool, then chop into tiny pieces — about pea-sized.",
      "Cook ground beef in a separate pan, drain fat, and let cool.",
      "Cook oats in plain water according to package directions.",
      "Scramble the egg in a dry non-stick pan (no butter, no oil needed).",
      "Combine liver, ground beef, oats, pumpkin puree, and egg.",
      "Cool completely. Liver is very rich — serve in smaller portions than usual.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Important: Liver should make up no more than 5% of your dog's diet. Too much vitamin A can be harmful. Use as a weekly rotation, not a daily staple. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "2–3 days max due to liver content" },
      { label: "Freezer", value: "Up to 6 weeks — freeze in small portions" },
      { label: "Serving Temp", value: "Room temperature only" },
      { label: "Frequency", value: "Serve 1–2× per week, not daily" },
    ],
    safeIngredients: ["Beef liver (in moderation)", "Lean beef", "Plain oats", "Pumpkin puree", "Eggs", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No raw liver to excess", "No added salt", "No spices", "No onion or garlic"],
    nutritionPerServing: { calories: 360, protein: "48g", fat: "10g", carbs: "22g", fiber: "4g" },
    allergens: ["beef", "egg"],
  },

  // ——— FISH ———
  {
    id: "salmon-quinoa",
    name: "Salmon & Quinoa",
    emoji: "🐟",
    protein: "fish",
    desc: "Omega-3 rich salmon with quinoa for a complete amino acid profile. Great for coat health.",
    tags: ["Omega-3", "Coat Health", "🐟 Fish", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 400,
    macros: { protein: 48, fat: 24, carbs: 28 },
    ingredients: [
      { qty: 5,  unit: "oz", item: "salmon fillet, boneless skinless" },
      { qty: 2,  unit: "oz", item: "quinoa (dry measure)" },
      { qty: 1,  unit: "oz", item: "spinach, chopped" },
      { qty: 1,  unit: "oz", item: "cucumber, diced small" },
      { qty: 0.5,unit: "oz", item: "blueberries" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Rinse quinoa thoroughly — this removes the bitter coating called saponin.",
      "Cook quinoa in 4 oz plain water for 15 minutes until water is absorbed.",
      "Place salmon on a baking sheet and bake at 350°F (175°C) for 15–18 minutes.",
      "Check salmon is fully cooked — it should flake easily with a fork. NO pink.",
      "Remove any remaining bones by feel — run your finger along the flesh.",
      "Flake salmon into small pieces and mix with quinoa, spinach, cucumber.",
      "Add blueberries last, mix gently, cool to room temperature before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Wild-caught salmon is preferred over farmed. Never feed raw salmon — it can contain a parasite (Neorickettsia helminthoeca) fatal to dogs. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 3 days — fish spoils faster than meat" },
      { label: "Freezer", value: "Up to 2 months in portioned freezer bags" },
      { label: "Serving Temp", value: "Cool room temperature only" },
      { label: "Daily Portion", value: "Use calculator above for your dog's weight" },
    ],
    safeIngredients: ["Cooked salmon (boneless)", "Quinoa", "Spinach", "Cucumber", "Blueberries", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["NEVER raw salmon", "No seasoning or salt", "No lemon (citrus)", "No soy sauce"],
    nutritionPerServing: { calories: 400, protein: "50g", fat: "12g", carbs: "26g", fiber: "3g" },
    allergens: ["fish"],
  },

  {
    id: "tuna-egg-rice",
    name: "Tuna & Egg Rice Bowl",
    emoji: "🥚",
    protein: "fish",
    desc: "Budget-friendly canned tuna with scrambled eggs and white rice. Quick and easy.",
    tags: ["Budget", "Quick", "🐟 Fish", "~15 min"],
    cookTime: 15,
    difficulty: "Easy",
    servingCalories: 350,
    macros: { protein: 50, fat: 18, carbs: 32 },
    ingredients: [
      { qty: 3,  unit: "oz", item: "canned tuna in water (no salt added), drained" },
      { qty: 2,  unit: "large", item: "eggs" },
      { qty: 3,  unit: "oz", item: "white rice, cooked" },
      { qty: 1,  unit: "oz", item: "peas (frozen, thawed)" },
      { qty: 0.5,unit: "oz", item: "shredded carrots" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook white rice in plain water — no salt, no butter.",
      "Crack eggs into a non-stick pan over low heat — no oil, no butter.",
      "Scramble eggs slowly until fully set with no runny parts.",
      "Drain canned tuna thoroughly — you want as little liquid as possible.",
      "Thaw peas under warm water or microwave for 30 seconds.",
      "Combine rice, scrambled eggs, tuna, peas, and carrots in a bowl.",
      "Mix well and cool completely before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Use tuna in water, NOT oil. Limit tuna to 2–3 times per week due to mercury content. Rotate with other proteins. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "2–3 days — eggs and fish need fresh rotation" },
      { label: "Freezer", value: "Not ideal — eggs change texture when frozen" },
      { label: "Serving Temp", value: "Room temperature" },
      { label: "Tuna Limit", value: "Max 2–3× per week due to mercury" },
    ],
    safeIngredients: ["Canned tuna in water", "Cooked eggs", "White rice", "Peas", "Carrots", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No tuna in oil", "No salted/flavored tuna", "No raw eggs (salmonella risk)", "No onion or garlic"],
    nutritionPerServing: { calories: 350, protein: "46g", fat: "9g", carbs: "30g", fiber: "2g" },
    allergens: ["fish", "egg", "pea"],
  },

  // ——— TURKEY ———
  {
    id: "turkey-pumpkin",
    name: "Turkey & Pumpkin Stew",
    emoji: "🦃",
    protein: "turkey",
    desc: "Gentle on sensitive stomachs. Pumpkin aids digestion and adds natural fiber.",
    tags: ["Sensitive Stomach", "Fiber", "🦃 Turkey", "~35 min"],
    cookTime: 35,
    difficulty: "Easy",
    servingCalories: 370,
    macros: { protein: 50, fat: 16, carbs: 34 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "ground turkey (93% lean or leaner)" },
      { qty: 3,  unit: "oz", item: "pumpkin puree (plain canned, NOT pie mix)" },
      { qty: 2,  unit: "oz", item: "sweet potato, boiled and mashed" },
      { qty: 1,  unit: "oz", item: "green peas" },
      { qty: 1,  unit: "oz", item: "celery, finely diced" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook ground turkey in a pan over medium heat, breaking apart with a spatula.",
      "Continue cooking until no pink remains — about 10–12 minutes. Drain any fat.",
      "Peel and cube sweet potato, boil for 10 minutes until soft, then mash.",
      "Steam celery and peas for 4 minutes until soft.",
      "In a bowl, combine cooked turkey, mashed sweet potato, peas, and celery.",
      "Stir in pumpkin puree — this adds fiber and helps digestion.",
      "Mix everything well and allow to cool fully before portioning.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Plain canned pumpkin (NOT pumpkin pie filling) is one of the best natural remedies for dog digestion. Great for both diarrhea and constipation. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 4 days in airtight container" },
      { label: "Freezer", value: "Up to 3 months, portion before freezing" },
      { label: "Serving Temp", value: "Slightly warm or room temperature" },
      { label: "Daily Portion", value: "See calculator for your dog's weight" },
    ],
    safeIngredients: ["Lean ground turkey", "Plain pumpkin puree", "Sweet potato", "Peas", "Celery", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No pumpkin pie spice or filling", "No turkey skin (high fat)", "No seasoning", "No cooked turkey bones"],
    nutritionPerServing: { calories: 370, protein: "48g", fat: "8g", carbs: "30g", fiber: "5g" },
    allergens: ["turkey", "pea"],
  },

  {
    id: "turkey-oat-veggie",
    name: "Turkey Oat Loaf",
    emoji: "🍞",
    protein: "turkey",
    desc: "A batch-cook loaf — slice into portions for easy daily serving. Great meal prep!",
    tags: ["Meal Prep", "Batch Cook", "🦃 Turkey", "~55 min"],
    cookTime: 55,
    difficulty: "Medium",
    servingCalories: 410,
    macros: { protein: 47, fat: 20, carbs: 33 },
    ingredients: [
      { qty: 8,  unit: "oz", item: "ground turkey" },
      { qty: 2,  unit: "oz", item: "rolled oats (plain)" },
      { qty: 2,  unit: "large", item: "eggs (binding agent)" },
      { qty: 2,  unit: "oz", item: "shredded carrots" },
      { qty: 1,  unit: "oz", item: "frozen spinach, thawed and squeezed dry" },
      { qty: 1,  unit: "oz", item: "plain pumpkin puree" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Lightly grease a loaf pan.",
      "In a large bowl, combine all ingredients — mix well with your hands.",
      "Pack the mixture firmly into the loaf pan.",
      "Bake for 45–50 minutes until internal temperature reaches 165°F (74°C).",
      "Let the loaf rest and cool for 20 minutes before slicing.",
      "Slice into portions appropriate for your dog's daily calorie needs.",
      "Wrap individual slices and store in fridge or freezer.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Score a grid on top before baking — this makes it easy to break into serving-size portions once cooked. Each slice is roughly 2 oz. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 4 days sliced in container" },
      { label: "Freezer", value: "Wrap individual slices, freeze up to 3 months" },
      { label: "Serving Temp", value: "Room temp or slightly warmed" },
      { label: "Batch Size", value: "~5 servings per loaf (adjust multiplier)" },
    ],
    safeIngredients: ["Ground turkey", "Plain oats", "Eggs", "Carrots", "Spinach", "Pumpkin puree", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No bread crumbs with seasoning", "No onion or garlic", "No salt", "No xylitol"],
    nutritionPerServing: { calories: 410, protein: "44g", fat: "10g", carbs: "28g", fiber: "4g" },
    allergens: ["turkey", "egg"],
  },
];

// ===================================================
//  Safety Reference Data
// ===================================================

const SAFETY_DATA = {
  safe: [
    "Cooked chicken, turkey, beef, fish (boneless)",
    "Brown rice, white rice, quinoa, oats",
    "Sweet potato, regular potato (cooked)",
    "Carrots, broccoli (small amounts)",
    "Peas, green beans, celery",
    "Spinach (in moderation)",
    "Pumpkin puree (plain)",
    "Blueberries, apples (no seeds), watermelon (no rind)",
    "Bananas (occasional treat)",
    "Plain cooked eggs",
    "Plain yogurt (no xylitol), cottage cheese",
    "Coconut oil, fish oil (supplements)",
    "Cucumber, zucchini",
  ],
  unsafe: [
    "Onions & garlic (ALL forms — powders, raw, cooked)",
    "Grapes & raisins (kidney failure)",
    "Chocolate & cocoa",
    "Xylitol (artificial sweetener — FATAL)",
    "Macadamia nuts",
    "Avocado (persin toxin)",
    "Alcohol (any amount)",
    "Caffeine (coffee, tea, energy drinks)",
    "Raw yeast dough",
    "Cooked bones (can splinter)",
    "Corn on the cob (choking hazard)",
    "Salt & heavily seasoned foods",
    "Nutmeg & many spices",
    "Raw salmon & trout (parasite risk)",
  ],
  caution: [
    "Liver — nutritious but limit to 5% of diet (excess vitamin A)",
    "Tuna — mercury; limit to 2–3× per week",
    "Dairy — some dogs are lactose intolerant",
    "Eggs — safe cooked, raw poses salmonella risk",
    "Spinach — fine in small amounts, oxalates in large amounts",
    "Broccoli — fine in moderation, GI upset in large quantities",
    "Tomatoes — ripe is OK, green/raw can be harmful",
    "Mushrooms — store-bought safe, wild mushrooms UNSAFE",
  ],
};
