// ===================================================
//  MealMutt — Recipe & Safety Data
// ===================================================

const RECIPES = [
  // ——— CHICKEN ———
  {
    id: "chicken-rice-veggie",
    name: "Classic Chicken & Rice",
    emoji: "🍚",
    protein: "chicken",
    desc: "A vet-approved staple: lean chicken, brown rice, and mixed veggies.",
    tags: ["Easy", "Vet Fave", "🍗 Chicken", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 420,   // per 8 oz batch serving
    macros: { protein: 50, fat: 20, carbs: 30 },
    // Ingredients given per 1 lb body weight per day → scaled in app
    // Base batch = ~8 oz cooked (serves 1 day for a 25-lb dog)
    ingredients: [
      { qty: 6,  unit: "oz", item: "boneless skinless chicken breast, diced" },
      { qty: 2,  unit: "oz", item: "brown rice (dry measure)" },
      { qty: 1,  unit: "oz", item: "carrots, finely chopped" },
      { qty: 0.5,unit: "oz", item: "frozen peas" },
      { qty: 0.5,unit: "oz", item: "spinach, finely chopped" },
      { qty: 1,  unit: "tsp", item: "fish oil (omega-3 supplement)" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Rinse brown rice and cook according to package — use plain water, no salt.",
      "While rice cooks, dice chicken breast into small, bite-sized pieces.",
      "Boil or steam chicken pieces for 12–15 minutes until fully cooked through (no pink).",
      "Steam or microwave carrots for 3–4 minutes until soft and mashable.",
      "Combine cooked rice, chicken, carrots, peas, and spinach in a large bowl.",
      "Let the mixture cool completely to room temperature before serving or storing.",
      "Drizzle fish oil over the portion before serving for omega-3 boost.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Dice everything small — dogs don't chew much! Pea size or smaller for toy breeds. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Store in airtight container for up to 4 days" },
      { label: "Freezer", value: "Freeze in daily portions for up to 3 months" },
      { label: "Serving Temp", value: "Room temperature or slightly warm — never hot" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight (see calculator)" },
    ],
    safeIngredients: ["Cooked chicken (boneless)", "Brown rice", "Carrots", "Peas", "Spinach", "Fish oil", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No cooked bones", "No grapes or raisins"],
    nutritionPerServing: { calories: 420, protein: "52g", fat: "9g", carbs: "28g", fiber: "3g" },
    allergens: ["chicken", "fish", "pea"],
  },

  {
    id: "chicken-sweet-potato",
    name: "Chicken & Sweet Potato",
    emoji: "🍠",
    protein: "chicken",
    desc: "Sweet potato provides fiber and beta-carotene — great for digestion and coat.",
    tags: ["Easy", "Digestion", "🍗 Chicken", "~25 min"],
    cookTime: 25,
    difficulty: "Easy",
    servingCalories: 390,
    macros: { protein: 45, fat: 18, carbs: 37 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "boneless chicken thigh, diced" },
      { qty: 3,  unit: "oz", item: "sweet potato, cubed" },
      { qty: 1,  unit: "oz", item: "green beans, chopped" },
      { qty: 0.5,unit: "oz", item: "blueberries (antioxidants)" },
      { qty: 1,  unit: "tsp", item: "coconut oil" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Peel and cube sweet potato into ½-inch pieces.",
      "Boil sweet potato for 10–12 minutes until fork-tender, then drain.",
      "While sweet potato cooks, dice chicken thigh into small pieces.",
      "Cook chicken in a dry pan over medium heat for 8–10 minutes until no pink remains.",
      "Steam green beans for 4–5 minutes until soft.",
      "Mash the sweet potato lightly — this helps smaller dogs eat it easier.",
      "Mix everything together with coconut oil and let cool fully before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Leave the sweet potato slightly chunky for larger dogs, fully mashed for puppies and small breeds. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 3–4 days in airtight container" },
      { label: "Freezer", value: "Freeze flat in zip-lock bags up to 2 months" },
      { label: "Serving Temp", value: "Room temp — microwave 10–15 sec if from fridge" },
      { label: "Daily Portion", value: "See calculator above for your dog's portion" },
    ],
    safeIngredients: ["Chicken thigh", "Sweet potato", "Green beans", "Blueberries", "Coconut oil", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No butter or salt", "No onion powder", "No macadamia nuts", "No xylitol"],
    nutritionPerServing: { calories: 390, protein: "44g", fat: "11g", carbs: "32g", fiber: "4g" },
    allergens: ["chicken"],
  },

  // ——— BEEF ———
  {
    id: "beef-veggie-bowl",
    name: "Beef & Veggie Bowl",
    emoji: "🥩",
    protein: "beef",
    desc: "Lean ground beef with mixed vegetables — iron-rich and protein-packed.",
    tags: ["Iron-Rich", "High Protein", "🥩 Beef", "~20 min"],
    cookTime: 20,
    difficulty: "Easy",
    servingCalories: 480,
    macros: { protein: 55, fat: 28, carbs: 17 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "lean ground beef (90/10 or leaner)" },
      { qty: 2,  unit: "oz", item: "zucchini, diced small" },
      { qty: 1.5,unit: "oz", item: "broccoli florets, finely chopped" },
      { qty: 1,  unit: "oz", item: "brown rice, cooked" },
      { qty: 0.5,unit: "oz", item: "carrots, shredded" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook lean ground beef in a pan over medium heat, breaking it apart as it cooks.",
      "Drain excess fat — too much fat can upset your dog's stomach.",
      "Steam broccoli and zucchini for 4–5 minutes until tender.",
      "Cook brown rice separately in plain water until done.",
      "Mix beef, vegetables, and rice together in a bowl.",
      "Let mixture cool to room temperature — feel the bottom of the bowl with your palm.",
      "Serve appropriate portion based on your dog's weight.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Use 90% lean ground beef or leaner to keep fat content low. High fat can cause pancreatitis. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "3–4 days in a sealed container" },
      { label: "Freezer", value: "Up to 3 months in portioned bags" },
      { label: "Serving Temp", value: "Cool to room temp before serving" },
      { label: "Daily Portion", value: "Calculated above based on body weight" },
    ],
    safeIngredients: ["Lean ground beef", "Zucchini", "Broccoli (small amounts)", "Brown rice", "Carrots", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No seasoning or spices", "No onions or garlic", "No soy sauce", "No fatty beef cuts"],
    nutritionPerServing: { calories: 480, protein: "58g", fat: "14g", carbs: "18g", fiber: "3g" },
    allergens: ["beef"],
  },

  {
    id: "beef-liver-oats",
    name: "Beef Liver & Oats",
    emoji: "🫀",
    protein: "beef",
    desc: "Liver is a nutrient powerhouse — vitamins A, B12, and iron. Use in moderation.",
    tags: ["Nutrient Dense", "Senior Fave", "🥩 Beef", "~25 min"],
    cookTime: 25,
    difficulty: "Medium",
    servingCalories: 360,
    macros: { protein: 52, fat: 22, carbs: 26 },
    ingredients: [
      { qty: 3,  unit: "oz", item: "beef liver, sliced" },
      { qty: 3,  unit: "oz", item: "lean ground beef" },
      { qty: 2,  unit: "oz", item: "rolled oats (plain, not instant)" },
      { qty: 1,  unit: "oz", item: "pumpkin puree (canned, plain)" },
      { qty: 0.5,unit: "oz", item: "egg (about ½ large egg)" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Bring a small pot of water to a boil, then cook beef liver for 8–10 minutes.",
      "Let liver cool, then chop into tiny pieces — about pea-sized.",
      "Cook ground beef in a separate pan, drain fat, and let cool.",
      "Cook oats in plain water according to package directions.",
      "Scramble the egg in a dry non-stick pan (no butter, no oil needed).",
      "Combine liver, ground beef, oats, pumpkin puree, and egg.",
      "Cool completely. Liver is very rich — serve in smaller portions than usual.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Important: Liver should make up no more than 5% of your dog's diet. Too much vitamin A can be harmful. Use as a weekly rotation, not a daily staple. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "2–3 days max due to liver content" },
      { label: "Freezer", value: "Up to 6 weeks — freeze in small portions" },
      { label: "Serving Temp", value: "Room temperature only" },
      { label: "Frequency", value: "Serve 1–2× per week, not daily" },
    ],
    safeIngredients: ["Beef liver (in moderation)", "Lean beef", "Plain oats", "Pumpkin puree", "Eggs", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No raw liver to excess", "No added salt", "No spices", "No onion or garlic"],
    nutritionPerServing: { calories: 360, protein: "48g", fat: "10g", carbs: "22g", fiber: "4g" },
    allergens: ["beef", "egg"],
  },

  // ——— FISH ———
  {
    id: "salmon-quinoa",
    name: "Salmon & Quinoa",
    emoji: "🐟",
    protein: "fish",
    desc: "Omega-3 rich salmon with quinoa for a complete amino acid profile. Great for coat health.",
    tags: ["Omega-3", "Coat Health", "🐟 Fish", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 400,
    macros: { protein: 48, fat: 24, carbs: 28 },
    ingredients: [
      { qty: 5,  unit: "oz", item: "salmon fillet, boneless skinless" },
      { qty: 2,  unit: "oz", item: "quinoa (dry measure)" },
      { qty: 1,  unit: "oz", item: "spinach, chopped" },
      { qty: 1,  unit: "oz", item: "cucumber, diced small" },
      { qty: 0.5,unit: "oz", item: "blueberries" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Rinse quinoa thoroughly — this removes the bitter coating called saponin.",
      "Cook quinoa in 4 oz plain water for 15 minutes until water is absorbed.",
      "Place salmon on a baking sheet and bake at 350°F (175°C) for 15–18 minutes.",
      "Check salmon is fully cooked — it should flake easily with a fork. NO pink.",
      "Remove any remaining bones by feel — run your finger along the flesh.",
      "Flake salmon into small pieces and mix with quinoa, spinach, cucumber.",
      "Add blueberries last, mix gently, cool to room temperature before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Wild-caught salmon is preferred over farmed. Never feed raw salmon — it can contain a parasite (Neorickettsia helminthoeca) fatal to dogs. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 3 days — fish spoils faster than meat" },
      { label: "Freezer", value: "Up to 2 months in portioned freezer bags" },
      { label: "Serving Temp", value: "Cool room temperature only" },
      { label: "Daily Portion", value: "Use calculator above for your dog's weight" },
    ],
    safeIngredients: ["Cooked salmon (boneless)", "Quinoa", "Spinach", "Cucumber", "Blueberries", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["NEVER raw salmon", "No seasoning or salt", "No lemon (citrus)", "No soy sauce"],
    nutritionPerServing: { calories: 400, protein: "50g", fat: "12g", carbs: "26g", fiber: "3g" },
    allergens: ["fish"],
  },

  {
    id: "tuna-egg-rice",
    name: "Tuna & Egg Rice Bowl",
    emoji: "🥚",
    protein: "fish",
    desc: "Budget-friendly canned tuna with scrambled eggs and white rice. Quick and easy.",
    tags: ["Budget", "Quick", "🐟 Fish", "~15 min"],
    cookTime: 15,
    difficulty: "Easy",
    servingCalories: 350,
    macros: { protein: 50, fat: 18, carbs: 32 },
    ingredients: [
      { qty: 3,  unit: "oz", item: "canned tuna in water (no salt added), drained" },
      { qty: 2,  unit: "large", item: "eggs" },
      { qty: 3,  unit: "oz", item: "white rice, cooked" },
      { qty: 1,  unit: "oz", item: "peas (frozen, thawed)" },
      { qty: 0.5,unit: "oz", item: "shredded carrots" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook white rice in plain water — no salt, no butter.",
      "Crack eggs into a non-stick pan over low heat — no oil, no butter.",
      "Scramble eggs slowly until fully set with no runny parts.",
      "Drain canned tuna thoroughly — you want as little liquid as possible.",
      "Thaw peas under warm water or microwave for 30 seconds.",
      "Combine rice, scrambled eggs, tuna, peas, and carrots in a bowl.",
      "Mix well and cool completely before serving.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Use tuna in water, NOT oil. Limit tuna to 2–3 times per week due to mercury content. Rotate with other proteins. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "2–3 days — eggs and fish need fresh rotation" },
      { label: "Freezer", value: "Not ideal — eggs change texture when frozen" },
      { label: "Serving Temp", value: "Room temperature" },
      { label: "Tuna Limit", value: "Max 2–3× per week due to mercury" },
    ],
    safeIngredients: ["Canned tuna in water", "Cooked eggs", "White rice", "Peas", "Carrots", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No tuna in oil", "No salted/flavored tuna", "No raw eggs (salmonella risk)", "No onion or garlic"],
    nutritionPerServing: { calories: 350, protein: "46g", fat: "9g", carbs: "30g", fiber: "2g" },
    allergens: ["fish", "egg", "pea"],
  },

  // ——— TURKEY ———
  {
    id: "turkey-pumpkin",
    name: "Turkey & Pumpkin Stew",
    emoji: "🦃",
    protein: "turkey",
    desc: "Gentle on sensitive stomachs. Pumpkin aids digestion and adds natural fiber.",
    tags: ["Sensitive Stomach", "Fiber", "🦃 Turkey", "~35 min"],
    cookTime: 35,
    difficulty: "Easy",
    servingCalories: 370,
    macros: { protein: 50, fat: 16, carbs: 34 },
    ingredients: [
      { qty: 6,  unit: "oz", item: "ground turkey (93% lean or leaner)" },
      { qty: 3,  unit: "oz", item: "pumpkin puree (plain canned, NOT pie mix)" },
      { qty: 2,  unit: "oz", item: "sweet potato, boiled and mashed" },
      { qty: 1,  unit: "oz", item: "green peas" },
      { qty: 1,  unit: "oz", item: "celery, finely diced" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Cook ground turkey in a pan over medium heat, breaking apart with a spatula.",
      "Continue cooking until no pink remains — about 10–12 minutes. Drain any fat.",
      "Peel and cube sweet potato, boil for 10 minutes until soft, then mash.",
      "Steam celery and peas for 4 minutes until soft.",
      "In a bowl, combine cooked turkey, mashed sweet potato, peas, and celery.",
      "Stir in pumpkin puree — this adds fiber and helps digestion.",
      "Mix everything well and allow to cool fully before portioning.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Plain canned pumpkin (NOT pumpkin pie filling) is one of the best natural remedies for dog digestion. Great for both diarrhea and constipation. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 4 days in airtight container" },
      { label: "Freezer", value: "Up to 3 months, portion before freezing" },
      { label: "Serving Temp", value: "Slightly warm or room temperature" },
      { label: "Daily Portion", value: "See calculator for your dog's weight" },
    ],
    safeIngredients: ["Lean ground turkey", "Plain pumpkin puree", "Sweet potato", "Peas", "Celery", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No pumpkin pie spice or filling", "No turkey skin (high fat)", "No seasoning", "No cooked turkey bones"],
    nutritionPerServing: { calories: 370, protein: "48g", fat: "8g", carbs: "30g", fiber: "5g" },
    allergens: ["turkey", "pea"],
  },

  {
    id: "turkey-oat-veggie",
    name: "Turkey Oat Loaf",
    emoji: "🍞",
    protein: "turkey",
    desc: "A batch-cook loaf — slice into portions for easy daily serving. Great meal prep!",
    tags: ["Meal Prep", "Batch Cook", "🦃 Turkey", "~55 min"],
    cookTime: 55,
    difficulty: "Medium",
    servingCalories: 410,
    macros: { protein: 47, fat: 20, carbs: 33 },
    ingredients: [
      { qty: 8,  unit: "oz", item: "ground turkey" },
      { qty: 2,  unit: "oz", item: "rolled oats (plain)" },
      { qty: 2,  unit: "large", item: "eggs (binding agent)" },
      { qty: 2,  unit: "oz", item: "shredded carrots" },
      { qty: 1,  unit: "oz", item: "frozen spinach, thawed and squeezed dry" },
      { qty: 1,  unit: "oz", item: "plain pumpkin puree" },
      { qty: 0.5, unit: "tsp", item: "eggshell powder (calcium)" },
      { qty: 1,   unit: "tsp", item: "wheat germ oil (vitamin E)" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C). Lightly grease a loaf pan.",
      "In a large bowl, combine all ingredients — mix well with your hands.",
      "Pack the mixture firmly into the loaf pan.",
      "Bake for 45–50 minutes until internal temperature reaches 165°F (74°C).",
      "Let the loaf rest and cool for 20 minutes before slicing.",
      "Slice into portions appropriate for your dog's daily calorie needs.",
      "Wrap individual slices and store in fridge or freezer.",
      "Mix in eggshell powder and wheat germ oil just before serving — do not cook these. Eggshell powder adds calcium; wheat germ oil adds vitamin E, both commonly deficient in homemade dog food.",
    ],
    tips: "Tip: Score a grid on top before baking — this makes it easy to break into serving-size portions once cooked. Each slice is roughly 2 oz. Eggshell powder and wheat germ oil are added to partially address calcium and vitamin E gaps common in homemade recipes.",
    storage: [
      { label: "Fridge", value: "Up to 4 days sliced in container" },
      { label: "Freezer", value: "Wrap individual slices, freeze up to 3 months" },
      { label: "Serving Temp", value: "Room temp or slightly warmed" },
      { label: "Batch Size", value: "~5 servings per loaf (adjust multiplier)" },
    ],
    safeIngredients: ["Ground turkey", "Plain oats", "Eggs", "Carrots", "Spinach", "Pumpkin puree", "Eggshell powder (calcium source)", "Wheat germ oil (vitamin E source)"],
    unsafeSwaps: ["No bread crumbs with seasoning", "No onion or garlic", "No salt", "No xylitol"],
    nutritionPerServing: { calories: 410, protein: "44g", fat: "10g", carbs: "28g", fiber: "4g" },
    allergens: ["turkey", "egg"],
  },

// ─────────────────────────────────────────
//  LAMB
// ─────────────────────────────────────────

  {
    id: "lamb-sweet-potato",
    name: "Lamb & Sweet Potato",
    emoji: "🍖",
    protein: "lamb",
    desc: "Novel protein for allergy-prone dogs — gentle on digestion, rich in zinc and B12.",
    tags: ["Novel Protein", "Allergy Friendly", "🐑 Lamb", "~35 min"],
    cookTime: 35,
    difficulty: "Easy",
    servingCalories: 460,
    macros: { protein: 48, fat: 28, carbs: 24 },
    allergens: ["lamb"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "ground lamb" },
      { qty: 2.5, unit: "oz",  item: "sweet potato, peeled and cubed" },
      { qty: 1,   unit: "oz",  item: "zucchini, diced" },
      { qty: 0.5, unit: "oz",  item: "spinach, finely chopped" },
      { qty: 1,   unit: "tsp", item: "coconut oil" },
    ],
    steps: [
      "Boil sweet potato cubes for 10–12 minutes until fork-tender. Drain and mash lightly.",
      "Brown ground lamb in a skillet over medium heat, breaking into small crumbles. No oil needed — lamb has enough natural fat.",
      "Cook until no pink remains, about 8–10 minutes. Drain any excess fat.",
      "Steam zucchini for 3–4 minutes until soft.",
      "Combine lamb, sweet potato, zucchini, and spinach. Mix well.",
      "Stir in coconut oil while the mixture is still warm.",
      "Cool completely before serving. Refrigerate unused portions immediately.",
    ],
    tips: "Tip: Lamb is a common 'novel protein' recommendation for dogs with chicken or beef allergies. Great rotation protein.",
    storage: [
      { label: "Fridge",        value: "Store in airtight container for up to 4 days" },
      { label: "Freezer",       value: "Freeze in daily portions for up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature or slightly warm — never hot" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight (see calculator)" },
    ],
    safeIngredients: ["Cooked ground lamb", "Sweet potato", "Zucchini", "Spinach", "Coconut oil"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No cooked bones", "No macadamia nuts"],
    nutritionPerServing: { calories: 460, protein: "48g", fat: "22g", carbs: "18g", fiber: "3g" },
  },

  {
    id: "lamb-rice-broccoli",
    name: "Lamb & Brown Rice Bowl",
    emoji: "🥣",
    protein: "lamb",
    desc: "Hearty lamb with brown rice and broccoli — a balanced, grain-inclusive meal for sensitive stomachs.",
    tags: ["Balanced", "Sensitive Stomach", "🐑 Lamb", "~40 min"],
    cookTime: 40,
    difficulty: "Easy",
    servingCalories: 490,
    macros: { protein: 45, fat: 25, carbs: 30 },
    allergens: ["lamb"],
    ingredients: [
      { qty: 5,   unit: "oz",  item: "ground lamb" },
      { qty: 2,   unit: "oz",  item: "brown rice (dry measure)" },
      { qty: 1.5, unit: "oz",  item: "broccoli, finely chopped" },
      { qty: 1,   unit: "oz",  item: "carrots, shredded" },
      { qty: 1,   unit: "tsp", item: "fish oil (omega-3 supplement)" },
    ],
    steps: [
      "Cook brown rice according to package directions using plain water — no salt.",
      "Brown ground lamb in a skillet over medium heat until fully cooked, about 8–10 minutes. Drain excess fat.",
      "Steam broccoli for 4–5 minutes until very soft — soft enough to mash between fingers.",
      "Combine lamb, rice, broccoli, and carrots in a bowl.",
      "Let cool to room temperature, then drizzle fish oil over the serving portion.",
      "Store in the fridge — do not add fish oil until serving time.",
    ],
    tips: "Tip: Chop broccoli very fine or mash it — large florets can be a choking risk and are harder to digest whole.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days in an airtight container" },
      { label: "Freezer",       value: "Up to 3 months — freeze in daily portions" },
      { label: "Serving Temp",  value: "Room temperature or slightly warm" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Ground lamb", "Brown rice", "Broccoli (cooked)", "Carrots", "Fish oil"],
    unsafeSwaps: ["No onion or garlic", "No salt", "No raw broccoli in large amounts (gas)", "No cooked bones"],
    nutritionPerServing: { calories: 490, protein: "45g", fat: "20g", carbs: "28g", fiber: "4g" },
  },

// ─────────────────────────────────────────
//  VENISON (novel protein — allergy-friendly)
// ─────────────────────────────────────────

  {
    id: "venison-sweet-potato",
    name: "Venison & Sweet Potato",
    emoji: "🦌",
    protein: "venison",
    desc: "Ultra-lean game meat — ideal for dogs with multiple meat allergies. High protein, low fat.",
    tags: ["Novel Protein", "Low Fat", "🦌 Venison", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 390,
    macros: { protein: 58, fat: 16, carbs: 26 },
    allergens: ["venison"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "ground venison" },
      { qty: 2.5, unit: "oz",  item: "sweet potato, peeled and cubed" },
      { qty: 1,   unit: "oz",  item: "green beans, chopped" },
      { qty: 0.5, unit: "oz",  item: "blueberries" },
      { qty: 1,   unit: "tsp", item: "coconut oil" },
    ],
    steps: [
      "Boil sweet potato until tender, about 10–12 minutes. Drain and cool.",
      "Cook ground venison in a skillet over medium heat. It's very lean — use the coconut oil to prevent sticking.",
      "Cook until fully browned, about 8 minutes. Drain if any liquid accumulates.",
      "Steam green beans for 3–4 minutes until soft.",
      "Combine all ingredients. Mash sweet potato slightly if desired.",
      "Cool fully before serving or storing.",
    ],
    tips: "Tip: Venison is one of the least common dog food proteins — excellent for dogs with multiple allergies who've exhausted chicken, beef, and lamb.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days in an airtight container" },
      { label: "Freezer",       value: "Up to 3 months in daily portions" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Ground venison", "Sweet potato", "Green beans", "Blueberries", "Coconut oil"],
    unsafeSwaps: ["No onion or garlic", "No salt or spices", "No wild venison from unknown sources (CWD risk)"],
    nutritionPerServing: { calories: 390, protein: "52g", fat: "12g", carbs: "22g", fiber: "4g" },
  },

  {
    id: "venison-quinoa-veggie",
    name: "Venison & Quinoa Power Bowl",
    emoji: "🌿",
    protein: "venison",
    desc: "Complete amino acid profile from quinoa plus lean venison — great for active and working dogs.",
    tags: ["High Protein", "Active Dogs", "🦌 Venison", "~35 min"],
    cookTime: 35,
    difficulty: "Easy",
    servingCalories: 420,
    macros: { protein: 55, fat: 18, carbs: 27 },
    allergens: ["venison"],
    ingredients: [
      { qty: 5,   unit: "oz",  item: "ground venison" },
      { qty: 2,   unit: "oz",  item: "quinoa (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely diced" },
      { qty: 1,   unit: "oz",  item: "zucchini, diced" },
      { qty: 0.5, unit: "oz",  item: "spinach" },
      { qty: 1,   unit: "tsp", item: "fish oil (omega-3 supplement)" },
    ],
    steps: [
      "Rinse quinoa thoroughly under cold water. Cook in plain water (2:1 water to quinoa) for 15 minutes. Fluff with a fork and cool.",
      "Brown ground venison in a skillet with a small drizzle of water or oil. Cook fully, about 8–10 minutes.",
      "Steam carrots and zucchini together for 4 minutes until soft.",
      "Combine all ingredients including spinach. The heat from the food will wilt the spinach.",
      "Cool completely, then add fish oil to serving portion before serving.",
    ],
    tips: "Tip: Quinoa must be rinsed before cooking to remove saponins — bitter compounds that can upset digestion. Don't skip the rinse.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature or slightly warm" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Ground venison", "Quinoa (rinsed)", "Carrots", "Zucchini", "Spinach", "Fish oil"],
    unsafeSwaps: ["No onion or garlic", "No salt", "No unrinsed quinoa", "No seasoning"],
    nutritionPerServing: { calories: 420, protein: "50g", fat: "14g", carbs: "24g", fiber: "3g" },
  },

// ─────────────────────────────────────────
//  NOVEL FISH (sardine, cod, whitefish)
// ─────────────────────────────────────────

  {
    id: "sardine-rice-veggie",
    name: "Sardine & Brown Rice",
    emoji: "🐟",
    protein: "fish",
    desc: "Canned sardines are one of the most omega-3-rich foods for dogs — affordable and incredibly nutritious.",
    tags: ["Omega-3", "Budget Friendly", "🐟 Fish", "~20 min"],
    cookTime: 20,
    difficulty: "Easy",
    servingCalories: 400,
    macros: { protein: 46, fat: 24, carbs: 30 },
    allergens: ["fish"],
    ingredients: [
      { qty: 4,   unit: "oz",  item: "canned sardines in water, drained" },
      { qty: 2,   unit: "oz",  item: "brown rice (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely chopped" },
      { qty: 1,   unit: "oz",  item: "sweet potato, cooked and mashed" },
      { qty: 0.5, unit: "oz",  item: "spinach, chopped" },
    ],
    steps: [
      "Cook brown rice in plain water according to package directions. Cool completely.",
      "Drain sardines thoroughly. Use sardines in water only — never in oil or with added salt.",
      "Mash sardines with a fork into small flakes.",
      "Steam or microwave carrots until soft, about 4 minutes.",
      "Combine rice, sardines, carrots, sweet potato, and spinach.",
      "Mix gently. Cool fully before serving.",
    ],
    tips: "Tip: Buy sardines in water with no added salt. Check the label — some canned fish has added sodium that's harmful to dogs.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days — fish-based meals spoil faster" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Sardines (water-packed, no salt)", "Brown rice", "Carrots", "Sweet potato", "Spinach"],
    unsafeSwaps: ["No sardines in oil", "No added salt", "No onion or garlic", "No fish with bones too large to chew safely"],
    nutritionPerServing: { calories: 400, protein: "44g", fat: "16g", carbs: "26g", fiber: "3g" },
  },

  {
    id: "cod-potato-veggie",
    name: "Cod & Potato Mash",
    emoji: "🐠",
    protein: "fish",
    desc: "Mild whitefish protein with potato — great for dogs with sensitive stomachs or multiple allergies.",
    tags: ["Sensitive Stomach", "Mild Flavor", "🐟 Fish", "~25 min"],
    cookTime: 25,
    difficulty: "Easy",
    servingCalories: 370,
    macros: { protein: 50, fat: 12, carbs: 38 },
    allergens: ["fish"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "cod fillet, boneless" },
      { qty: 3,   unit: "oz",  item: "white potato, peeled and cubed" },
      { qty: 1,   unit: "oz",  item: "green beans, chopped" },
      { qty: 0.5, unit: "oz",  item: "carrots, finely grated" },
      { qty: 1,   unit: "tsp", item: "coconut oil" },
    ],
    steps: [
      "Boil potato cubes for 12–15 minutes until tender. Drain and mash — no butter, no milk, no salt.",
      "Poach cod by placing fillet in simmering water for 8–10 minutes until it flakes easily.",
      "Remove all bones carefully. Flake cod into small pieces.",
      "Steam green beans for 3–4 minutes until soft.",
      "Combine mashed potato, cod, green beans, and carrots.",
      "Stir in coconut oil. Cool completely before serving.",
    ],
    tips: "Tip: Always double-check for bones in fish before mixing — run your fingers along the flesh against the grain.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days — fish spoils faster than meat" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Cooked cod (boneless)", "White potato", "Green beans", "Carrots", "Coconut oil"],
    unsafeSwaps: ["No salt or butter in potatoes", "No raw fish", "No onion or garlic", "Check for all bones"],
    nutritionPerServing: { calories: 370, protein: "46g", fat: "8g", carbs: "30g", fiber: "4g" },
  },

  {
    id: "whitefish-oat-veggie",
    name: "Whitefish & Oat Bowl",
    emoji: "🌊",
    protein: "fish",
    desc: "Tilapia or cod with oats and veggies — fiber-rich, grain-inclusive, and easy on the gut.",
    tags: ["High Fiber", "Gut Health", "🐟 Fish", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 380,
    macros: { protein: 46, fat: 14, carbs: 40 },
    allergens: ["fish"],
    ingredients: [
      { qty: 5,   unit: "oz",  item: "tilapia fillet, boneless" },
      { qty: 2,   unit: "oz",  item: "rolled oats (dry measure)" },
      { qty: 1,   unit: "oz",  item: "zucchini, diced" },
      { qty: 1,   unit: "oz",  item: "sweet potato, cooked and diced" },
      { qty: 0.5, unit: "oz",  item: "blueberries" },
    ],
    steps: [
      "Cook oats in plain water (no salt, no milk) until fully soft. Cool completely.",
      "Poach tilapia in simmering water for 6–8 minutes until it flakes easily. Check for bones.",
      "Flake fish into small pieces, removing any bones found.",
      "Steam zucchini for 3 minutes until soft.",
      "Combine oats, fish, zucchini, sweet potato, and blueberries.",
      "Mix gently and cool fully before serving.",
    ],
    tips: "Tip: Use plain rolled oats, not instant oats or flavored packets. Tilapia is a budget-friendly whitefish — you can also use any boneless white-fleshed fish.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Cooked tilapia (boneless)", "Rolled oats", "Zucchini", "Sweet potato", "Blueberries"],
    unsafeSwaps: ["No flavored oats", "No raw fish", "No salt", "Always remove all fish bones"],
    nutritionPerServing: { calories: 380, protein: "42g", fat: "10g", carbs: "34g", fiber: "5g" },
  },

// ─────────────────────────────────────────
//  DUCK (novel protein)
// ─────────────────────────────────────────

  {
    id: "duck-sweet-potato",
    name: "Duck & Sweet Potato",
    emoji: "🦆",
    protein: "duck",
    desc: "Rich, flavorful novel protein — popular in commercial limited-ingredient diets, now homemade.",
    tags: ["Novel Protein", "Limited Ingredient", "🦆 Duck", "~40 min"],
    cookTime: 40,
    difficulty: "Medium",
    servingCalories: 500,
    macros: { protein: 44, fat: 32, carbs: 24 },
    allergens: ["duck"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "duck breast, boneless and skinless" },
      { qty: 2.5, unit: "oz",  item: "sweet potato, peeled and cubed" },
      { qty: 1,   unit: "oz",  item: "green beans, chopped" },
      { qty: 0.5, unit: "oz",  item: "blueberries" },
    ],
    steps: [
      "Boil sweet potato for 10–12 minutes until tender. Drain and set aside.",
      "Dice duck breast into small pieces — removing all skin (duck skin is high fat and not appropriate in large amounts).",
      "Poach duck in simmering water for 12–15 minutes until fully cooked through (no pink).",
      "Steam green beans for 3–4 minutes until soft.",
      "Combine duck, sweet potato, green beans, and blueberries.",
      "Cool fully before serving.",
    ],
    tips: "Tip: Remove all duck skin before cooking — it's too high in fat for regular feeding. Ground duck is easier to work with if available from a butcher.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days in an airtight container" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Cooked duck (skinless, boneless)", "Sweet potato", "Green beans", "Blueberries"],
    unsafeSwaps: ["No duck skin", "No cooked bones", "No onion or garlic", "No salt or seasoning"],
    nutritionPerServing: { calories: 500, protein: "46g", fat: "24g", carbs: "20g", fiber: "4g" },
  },

// ─────────────────────────────────────────
//  RABBIT (novel protein)
// ─────────────────────────────────────────

  {
    id: "rabbit-rice-veggie",
    name: "Rabbit & White Rice",
    emoji: "🐇",
    protein: "rabbit",
    desc: "Ultra-lean novel protein — one of the best options for dogs with multiple protein allergies.",
    tags: ["Novel Protein", "Allergy Friendly", "🐇 Rabbit", "~35 min"],
    cookTime: 35,
    difficulty: "Medium",
    servingCalories: 380,
    macros: { protein: 58, fat: 14, carbs: 28 },
    allergens: ["rabbit"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "rabbit meat, boneless" },
      { qty: 2,   unit: "oz",  item: "white rice (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely diced" },
      { qty: 0.5, unit: "oz",  item: "zucchini, diced" },
      { qty: 1,   unit: "tsp", item: "fish oil (omega-3 supplement)" },
    ],
    steps: [
      "Cook white rice in plain water. Cool completely.",
      "Dice rabbit into small pieces, removing all bones.",
      "Poach rabbit in simmering water for 15–18 minutes until fully cooked through.",
      "Steam carrots and zucchini for 4 minutes until tender.",
      "Combine all ingredients and mix well.",
      "Cool fully, then add fish oil to each serving portion.",
    ],
    tips: "Tip: Rabbit can be harder to source — check with local butchers, ethnic grocery stores, or online pet food suppliers that carry human-grade rabbit.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Cooked rabbit (boneless)", "White rice", "Carrots", "Zucchini", "Fish oil"],
    unsafeSwaps: ["No cooked bones", "No onion or garlic", "No salt", "Remove all small bones carefully"],
    nutritionPerServing: { calories: 380, protein: "54g", fat: "10g", carbs: "24g", fiber: "2g" },
  },

// ─────────────────────────────────────────
//  ORGAN MEAT COMBOS
// ─────────────────────────────────────────

  {
    id: "beef-heart-rice",
    name: "Beef Heart & Brown Rice",
    emoji: "❤️",
    protein: "beef",
    desc: "Beef heart is a muscle meat — not an organ — packed with taurine, CoQ10, and iron. Great for heart health.",
    tags: ["Heart Health", "Taurine-Rich", "🥩 Beef", "~35 min"],
    cookTime: 35,
    difficulty: "Medium",
    servingCalories: 450,
    macros: { protein: 52, fat: 22, carbs: 26 },
    allergens: ["beef"],
    ingredients: [
      { qty: 5,   unit: "oz",  item: "beef heart, trimmed and diced" },
      { qty: 2,   unit: "oz",  item: "brown rice (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely chopped" },
      { qty: 1,   unit: "oz",  item: "spinach, chopped" },
      { qty: 0.5, unit: "oz",  item: "broccoli, finely chopped" },
    ],
    steps: [
      "Cook brown rice in plain water. Set aside to cool.",
      "Trim any visible connective tissue and excess fat from the beef heart.",
      "Dice heart into small, pea-sized pieces.",
      "Boil heart pieces for 15–20 minutes until fully cooked through.",
      "Steam carrots and broccoli for 4–5 minutes until soft.",
      "Combine all ingredients. Cool fully before serving.",
    ],
    tips: "Tip: Beef heart is classified as a muscle meat, not an organ, which means it can make up a larger portion of the diet compared to liver or kidney. Ask your butcher — it's usually inexpensive.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Beef heart (cooked)", "Brown rice", "Carrots", "Spinach", "Broccoli (cooked)"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No raw heart for immunocompromised dogs"],
    nutritionPerServing: { calories: 450, protein: "50g", fat: "18g", carbs: "24g", fiber: "4g" },
  },

  {
    id: "chicken-liver-rice",
    name: "Chicken Liver & Rice",
    emoji: "🫀",
    protein: "chicken",
    desc: "Vitamin A powerhouse — use once or twice a week as a protein rotation, not a daily staple.",
    tags: ["Nutrient Dense", "Vitamin A", "🍗 Chicken", "~25 min"],
    cookTime: 25,
    difficulty: "Easy",
    servingCalories: 410,
    macros: { protein: 50, fat: 22, carbs: 28 },
    allergens: ["chicken"],
    ingredients: [
      { qty: 4,   unit: "oz",  item: "chicken liver" },
      { qty: 2,   unit: "oz",  item: "white rice (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely chopped" },
      { qty: 0.5, unit: "oz",  item: "sweet potato, cooked" },
      { qty: 0.5, unit: "oz",  item: "green beans, chopped" },
    ],
    steps: [
      "Cook white rice in plain water. Cool completely.",
      "Rinse chicken livers and trim any connective tissue or green spots.",
      "Boil livers in plain water for 10–12 minutes until fully cooked through and no pink remains.",
      "Chop cooked livers into small pieces.",
      "Steam carrots and green beans for 4 minutes until soft.",
      "Combine all ingredients. Cool fully before serving.",
    ],
    tips: "Tip: Liver is rich in Vitamin A — too much causes toxicity. Limit to no more than 5% of your dog's weekly diet. Mix with other proteins rather than feeding daily.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days — organ meats spoil faster" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight — feed 2×/week max" },
    ],
    safeIngredients: ["Cooked chicken liver", "White rice", "Carrots", "Sweet potato", "Green beans"],
    unsafeSwaps: ["No onion or garlic", "No salt", "Do not feed daily — liver is rich, use as rotation"],
    nutritionPerServing: { calories: 410, protein: "48g", fat: "18g", carbs: "22g", fiber: "3g" },
  },

  {
    id: "beef-kidney-oat",
    name: "Beef Kidney & Oat Bowl",
    emoji: "🫘",
    protein: "beef",
    desc: "Kidney is rich in B12, riboflavin, and selenium. A nutrient-dense rotation meal — feed sparingly.",
    tags: ["Nutrient Dense", "Senior Fave", "🥩 Beef", "~30 min"],
    cookTime: 30,
    difficulty: "Medium",
    servingCalories: 420,
    macros: { protein: 50, fat: 20, carbs: 30 },
    allergens: ["beef"],
    ingredients: [
      { qty: 3,   unit: "oz",  item: "beef kidney, trimmed" },
      { qty: 2,   unit: "oz",  item: "ground beef, lean" },
      { qty: 2,   unit: "oz",  item: "rolled oats (dry measure)" },
      { qty: 1,   unit: "oz",  item: "carrots, finely diced" },
      { qty: 0.5, unit: "oz",  item: "spinach" },
    ],
    steps: [
      "Cook rolled oats in plain water until soft. Cool and set aside.",
      "Rinse beef kidney and trim any visible fat or sinew.",
      "Cut kidney into small pieces and boil for 15 minutes in plain water. Drain.",
      "Cook ground beef separately in a skillet until browned. Drain fat.",
      "Steam carrots for 4 minutes until soft.",
      "Combine all ingredients including spinach. Mix well and cool fully.",
    ],
    tips: "Tip: Mix kidney with a lean muscle meat like ground beef to dilute the richness. Feed no more than twice a week — kidney is an organ meat and should not dominate the diet.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs — feed 2×/week max" },
    ],
    safeIngredients: ["Cooked beef kidney", "Lean ground beef", "Rolled oats", "Carrots", "Spinach"],
    unsafeSwaps: ["No onion or garlic", "No salt", "Do not overfeed organ meats — use as rotation"],
    nutritionPerServing: { calories: 420, protein: "48g", fat: "16g", carbs: "26g", fiber: "4g" },
  },

  {
    id: "turkey-liver-veggie",
    name: "Turkey & Liver Medley",
    emoji: "🦃",
    protein: "turkey",
    desc: "Ground turkey with a small amount of turkey liver for B vitamins — a balanced organ blend.",
    tags: ["Balanced", "B-Vitamins", "🦃 Turkey", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 430,
    macros: { protein: 52, fat: 22, carbs: 26 },
    allergens: ["turkey", "chicken"],
    ingredients: [
      { qty: 4.5, unit: "oz",  item: "ground turkey" },
      { qty: 1.5, unit: "oz",  item: "chicken liver" },
      { qty: 1.5, unit: "oz",  item: "sweet potato, cooked and diced" },
      { qty: 1,   unit: "oz",  item: "broccoli, finely chopped" },
      { qty: 0.5, unit: "oz",  item: "carrots, shredded" },
    ],
    steps: [
      "Cook ground turkey in a skillet over medium heat until fully browned. Break into small crumbles.",
      "Boil chicken livers for 10 minutes until cooked through. Chop into small pieces.",
      "Steam broccoli for 4 minutes until soft.",
      "Combine ground turkey, liver, sweet potato, broccoli, and carrots.",
      "Mix thoroughly and cool fully before serving.",
    ],
    tips: "Tip: The liver should be roughly 25% of the total meat portion — enough for nutritional benefit without risking Vitamin A overload.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days (organ meats reduce shelf life)" },
      { label: "Freezer",       value: "Up to 2 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight — rotate with other meals" },
    ],
    safeIngredients: ["Ground turkey", "Cooked chicken liver", "Sweet potato", "Broccoli", "Carrots"],
    unsafeSwaps: ["No onion or garlic", "No salt", "Do not feed liver-heavy meals daily"],
    nutritionPerServing: { calories: 430, protein: "50g", fat: "18g", carbs: "22g", fiber: "3g" },
  },

// ─────────────────────────────────────────
//  ADDITIONAL CHICKEN & BEEF VARIANTS
// ─────────────────────────────────────────

  {
    id: "chicken-thigh-veggie",
    name: "Chicken Thigh & Veggie Mash",
    emoji: "🍗",
    protein: "chicken",
    desc: "Fattier than breast — great for underweight dogs, puppies, and picky eaters who need palatability.",
    tags: ["Picky Eaters", "Puppies", "🍗 Chicken", "~30 min"],
    cookTime: 30,
    difficulty: "Easy",
    servingCalories: 470,
    macros: { protein: 46, fat: 30, carbs: 24 },
    allergens: ["chicken"],
    ingredients: [
      { qty: 6,   unit: "oz",  item: "chicken thigh, boneless skinless" },
      { qty: 1.5, unit: "oz",  item: "sweet potato, cooked and mashed" },
      { qty: 1,   unit: "oz",  item: "green beans, chopped" },
      { qty: 1,   unit: "oz",  item: "carrots, finely diced" },
      { qty: 1,   unit: "tsp", item: "coconut oil" },
    ],
    steps: [
      "Dice chicken thighs into small pieces.",
      "Boil chicken in plain water for 15 minutes until fully cooked. No pink should remain.",
      "Steam green beans and carrots together for 4 minutes.",
      "Mash sweet potato (already cooked) with coconut oil.",
      "Combine chicken, vegetables, and sweet potato mash.",
      "Cool completely before serving.",
    ],
    tips: "Tip: Thighs are more calorie-dense than breast — adjust portion slightly downward for overweight or sedentary dogs.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs (reduce slightly for overweight dogs)" },
    ],
    safeIngredients: ["Cooked chicken thigh (boneless)", "Sweet potato", "Green beans", "Carrots", "Coconut oil"],
    unsafeSwaps: ["No cooked bones", "No onion or garlic", "No salt"],
    nutritionPerServing: { calories: 470, protein: "46g", fat: "24g", carbs: "20g", fiber: "4g" },
  },

  {
    id: "beef-pumpkin-oat",
    name: "Beef & Pumpkin Oat Loaf",
    emoji: "🎃",
    protein: "beef",
    desc: "A batch-cook loaf you can slice and freeze — pumpkin for digestion, oats for fiber.",
    tags: ["Batch Cook", "Digestion", "🥩 Beef", "~50 min"],
    cookTime: 50,
    difficulty: "Medium",
    servingCalories: 480,
    macros: { protein: 48, fat: 26, carbs: 26 },
    allergens: ["beef", "egg"],
    ingredients: [
      { qty: 8,     unit: "oz",    item: "lean ground beef" },
      { qty: 2,     unit: "oz",    item: "rolled oats (dry measure)" },
      { qty: 2,     unit: "oz",    item: "canned pumpkin (plain, not pie filling)" },
      { qty: 1,     unit: "large", item: "egg" },
      { qty: 1,     unit: "oz",    item: "carrots, finely shredded" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C).",
      "In a large bowl, combine ground beef, oats, pumpkin, egg, and shredded carrots.",
      "Mix thoroughly with your hands until fully combined.",
      "Press mixture into a loaf pan (8x4 inch) or shape into a log on a baking sheet.",
      "Bake for 40–45 minutes until internal temperature reaches 165°F.",
      "Let cool completely. Slice into daily portions and freeze what you won't use in 3 days.",
    ],
    tips: "Tip: Use 100% pure pumpkin puree — not pumpkin pie filling, which contains spices and sugar. The egg acts as a binder so the loaf holds its shape for slicing.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days once sliced" },
      { label: "Freezer",       value: "Freeze individual slices for up to 3 months" },
      { label: "Serving Temp",  value: "Thaw overnight in fridge, serve at room temp" },
      { label: "Daily Portion", value: "One slice ≈ 1 day's food for a 25-lb dog" },
    ],
    safeIngredients: ["Lean ground beef", "Rolled oats", "Pure pumpkin puree", "Egg", "Carrots"],
    unsafeSwaps: ["No pumpkin pie filling (contains spices/sugar)", "No salt", "No onion or garlic"],
    nutritionPerServing: { calories: 480, protein: "48g", fat: "22g", carbs: "22g", fiber: "5g" },
  },

  {
    id: "ground-turkey-zucchini",
    name: "Turkey Zucchini Scramble",
    emoji: "🥒",
    protein: "turkey",
    desc: "Light and low-carb — ideal for overweight dogs or seniors needing fewer calories.",
    tags: ["Low Calorie", "Senior", "🦃 Turkey", "~20 min"],
    cookTime: 20,
    difficulty: "Easy",
    servingCalories: 340,
    macros: { protein: 56, fat: 22, carbs: 22 },
    allergens: ["turkey"],
    ingredients: [
      { qty: 7,   unit: "oz",  item: "ground turkey" },
      { qty: 2,   unit: "oz",  item: "zucchini, finely diced" },
      { qty: 1,   unit: "oz",  item: "spinach" },
      { qty: 0.5, unit: "oz",  item: "blueberries" },
      { qty: 1,   unit: "tsp", item: "fish oil (omega-3 supplement)" },
    ],
    steps: [
      "Cook ground turkey in a skillet over medium heat, breaking into small crumbles.",
      "Cook until fully browned — about 8–10 minutes. Drain any excess liquid.",
      "Add zucchini to the pan and cook for 2–3 minutes until just softened.",
      "Add spinach and stir for 1 minute until wilted.",
      "Remove from heat. Add blueberries once cooled.",
      "Add fish oil just before serving.",
    ],
    tips: "Tip: This is one of the fastest recipes in the library. Great for busy nights. The low carb profile makes it a good fit for overweight or diabetic-prone dogs.",
    storage: [
      { label: "Fridge",        value: "Up to 4 days" },
      { label: "Freezer",       value: "Up to 3 months" },
      { label: "Serving Temp",  value: "Room temperature" },
      { label: "Daily Portion", value: "~1 oz per 10 lbs body weight" },
    ],
    safeIngredients: ["Ground turkey", "Zucchini", "Spinach", "Blueberries", "Fish oil"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No grapes (use blueberries only)"],
    nutritionPerServing: { calories: 340, protein: "52g", fat: "16g", carbs: "16g", fiber: "3g" },
  },

  {
    id: "turkey-oat-loaf",
    name: "Turkey Oat Loaf",
    emoji: "🍞",
    protein: "turkey",
    desc: "A batch-cook loaf you can slice and freeze — easy weekday meals for the whole week.",
    tags: ["Batch Cook", "Meal Prep", "🦃 Turkey", "~55 min"],
    cookTime: 55,
    difficulty: "Medium",
    servingCalories: 440,
    macros: { protein: 50, fat: 22, carbs: 28 },
    allergens: ["turkey", "egg"],
    ingredients: [
      { qty: 8,   unit: "oz",    item: "ground turkey" },
      { qty: 2,   unit: "oz",    item: "rolled oats (dry measure)" },
      { qty: 1,   unit: "large", item: "egg" },
      { qty: 1.5, unit: "oz",    item: "carrots, finely shredded" },
      { qty: 1,   unit: "oz",    item: "sweet potato, cooked and mashed" },
      { qty: 0.5, unit: "oz",    item: "spinach, finely chopped" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C).",
      "In a large bowl, combine ground turkey, oats, egg, carrots, sweet potato, and spinach.",
      "Mix thoroughly with your hands until fully combined — the egg binds everything together.",
      "Press mixture into a greased 8x4 inch loaf pan or shape into a log on a lined baking sheet.",
      "Bake for 45–50 minutes until internal temperature reaches 165°F.",
      "Let cool completely before slicing. Slice into daily portions.",
      "Refrigerate what you'll use in 3 days — freeze the rest individually wrapped.",
    ],
    tips: "Tip: Use a meat thermometer — turkey loaf can look done on the outside while still undercooked inside. 165°F is the safe internal temp.",
    storage: [
      { label: "Fridge",        value: "Up to 3 days once sliced" },
      { label: "Freezer",       value: "Freeze individual slices for up to 3 months" },
      { label: "Serving Temp",  value: "Thaw overnight in fridge, serve at room temperature" },
      { label: "Daily Portion", value: "One slice ≈ 1 day's food for a 25-lb dog" },
    ],
    safeIngredients: ["Ground turkey", "Rolled oats", "Egg", "Carrots", "Sweet potato", "Spinach"],
    unsafeSwaps: ["No onion or garlic", "No salt or seasoning", "No cooked bones"],
    nutritionPerServing: { calories: 440, protein: "48g", fat: "18g", carbs: "24g", fiber: "4g" },
  },
];

// ===================================================
//  Safety Reference Data
// ===================================================

const SAFETY_DATA = {
  safe: [
    "Cooked chicken, turkey, beef, fish (boneless)",
    "Brown rice, white rice, quinoa, oats",
    "Sweet potato, regular potato (cooked)",
    "Carrots, broccoli (small amounts)",
    "Peas, green beans, celery",
    "Spinach (in moderation)",
    "Pumpkin puree (plain)",
    "Blueberries, apples (no seeds), watermelon (no rind)",
    "Bananas (occasional treat)",
    "Plain cooked eggs",
    "Plain yogurt (no xylitol), cottage cheese",
    "Coconut oil, fish oil (supplements)",
    "Cucumber, zucchini",
  ],
  unsafe: [
    "Onions & garlic (ALL forms — powders, raw, cooked)",
    "Grapes & raisins (kidney failure)",
    "Chocolate & cocoa",
    "Xylitol (artificial sweetener — FATAL)",
    "Macadamia nuts",
    "Avocado (persin toxin)",
    "Alcohol (any amount)",
    "Caffeine (coffee, tea, energy drinks)",
    "Raw yeast dough",
    "Cooked bones (can splinter)",
    "Corn on the cob (choking hazard)",
    "Salt & heavily seasoned foods",
    "Nutmeg & many spices",
    "Raw salmon & trout (parasite risk)",
  ],
  caution: [
    "Liver — nutritious but limit to 5% of diet (excess vitamin A)",
    "Tuna — mercury; limit to 2–3× per week",
    "Dairy — some dogs are lactose intolerant",
    "Eggs — safe cooked, raw poses salmonella risk",
    "Spinach — fine in small amounts, oxalates in large amounts",
    "Broccoli — fine in moderation, GI upset in large quantities",
    "Tomatoes — ripe is OK, green/raw can be harmful",
    "Mushrooms — store-bought safe, wild mushrooms UNSAFE",
  ],
};
